### Dúvidas:

- Total de colunas: 11
    - só muda se houver a solicitação de inclusão de mais campos

- Nome da aba é sempre "dados"?
    - Sim!

- Qual é a origem dos relatórios?
    - Resp: eles são extraídos do sistema de venda.

- Data é a data de realização da venda?
    - Sim!
    
- Quem são os compradores?
    - O nome do arquivo tem algo a ver com isso?
        - Nome do arquivo é configurado da seguinte forma:

        `nome do segmento - país onde foi realizada a venda`



Passo a passo:

- Criar uma planilha em branco
- Replicar as colunas que existem nos relatórios (11 colunas)
- Inserir duas colunas novas: Segmento e País
- Percorrer todos os arquivos, copiar os dados, colar na planilha consolidado e preencher
as informações de segmento e país

In [39]:
import pandas as pd
import os
import datetime

In [40]:
data = datetime.datetime.now()

In [41]:
colunas = [
    'Segmento',
    'País',
    'Produto',
    'Qtde de Unidades Vendidas',
    'Preço Unitário',
    'Valor Total',
    'Desconto',
    'Valor Total c/ Desconto',
    'Custo Total',
    'Lucro',
    'Data',
    'Mês',
    'Ano'
]
consolidado = pd.DataFrame(columns= colunas)

In [42]:
type(consolidado)

pandas.core.frame.DataFrame

In [43]:
consolidado

Empty DataFrame
Columns: [Segmento, País, Produto, Qtde de Unidades Vendidas, Preço Unitário, Valor Total, Desconto, Valor Total c/ Desconto, Custo Total, Lucro, Data, Mês, Ano]
Index: []

In [44]:
arquivos = os.listdir("C:\\Users\\Cliente\\Downloads\\consolidando_planilhas\\planilhas")

In [45]:
for excel in arquivos:

    if excel.endswith('xlsx'):
        dados_arquivo = excel.split('-')
        segmento = dados_arquivo[0]
        pais = dados_arquivo[1].replace('.xlsx', '')

        try:
            df = pd.read_excel(f'C:\\Users\\Cliente\\Downloads\\consolidando_planilhas\\planilhas\\{excel}')
            df.insert(0, 'Segmento', segmento)
            df.insert(1, 'País', pais)
            consolidado = pd.concat([consolidado, df])
        except:
            with open('log_erros.txt', 'a') as arquivo:
                arquivo.write(f'Erro ao tentar consolidar o arquivo {excel}.')
    else:
        with open('log_erros.txt', 'a') as arquivo:
            arquivo.write(f'O arquivo {excel} não é um arquivo Excel válido.')

C:\Users\Cliente\AppData\Local\Temp\ipykernel_13568\3503644124.py:12: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  consolidado = pd.concat([consolidado, df])

In [46]:
consolidado

,Segmento,País,Produto,Qtde de Unidades Vendidas,Preço Unitário,Valor Total,Desconto,Valor Total c/ Desconto,Custo Total,Lucro,Data,Mês,Ano
0,Governo,Alemanha,Produto 1,1321,20,26420,0.00,26420.00,14531.0,11889.00,2019-01-01,Janeiro,2019
1,Governo,Alemanha,Produto 1,1513,350,529550,0.00,529550.00,432718.0,96832.00,2019-12-01,Dezembro,2019
2,Governo,Alemanha,Produto 2,2146,7,15022,0.00,15022.00,10730.0,4292.00,2019-09-01,Setembro,2019
3,Governo,Alemanha,Produto 3,1006,350,352100,0.00,352100.00,261560.0,90540.00,2019-06-01,Junho,2019
4,Governo,Alemanha,Produto 3,1513,350,529550,0.00,529550.00,393380.0,136170.00,2019-12-01,Dezembro,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15,Vendas online,França,Produto 3,2425.5,12,29106,3201.66,25904.34,7276.5,18627.84,2019-07-01,Julho,2019
16,Vendas online,França,Produto 5,1734.0,12,20808,2288.88,18519.12,5202.0,13317.12,2019-01-01,Janeiro,2019
17,Vendas online,França,Produto 3,1393.0,12,16716,2340.24,14375.76,4179.0,10196.76,2019-10-01,Outubro,2019
18,Vendas online,França,Produto 6,1393.0,12,16716,2340.24,14375.76,4179.0,10196.76,2019-10-01,Outubro,2019
19,Vendas online,França,Produto 6,2475.0,12,29700,4158.00,25542.00,7425.0,18117.00,2019-08-01,Agosto,2019

In [47]:
consolidado.shape

(700, 13)

In [48]:
consolidado.to_excel(f"Report-consolidado-{data.strftime('%d-%m-%Y')}.xlsx", 
                     index = False,
                     sheet_name = "Report consolidado")